name: deploy-to-stg-test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-2-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName 18.222.230.190
            User deploy
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/deploy/stg
          remote_host: 18.222.230.190
          remote_user: deploy
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Bring up the server
        run: ssh staging 'cd /home/deployment; docker-compose up -d --force --build'
