name: deploy-to-stg-test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-2-stg:
    runs-on: ubuntu-latest
    steps:
    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Deploy with rsync
      run: rsync -e "ssh -o StrictHostKeyChecking=no" -avz /src deploy@18.222.230.190:/home/deploy/stg/